[svn r3898] (BNK)makeversion unterstuetzt jetzt auch hg Repositories

diff --git a/misc/makeversion b/misc/makeversion
--- a/misc/makeversion
+++ b/misc/makeversion
@@ -17,8 +17,14 @@ if [ -z "$date" ]; then
   echo 1>&2 "Getting SVN version info failed => Trying GIT"
   date=$(git log -1 --date=short|grep ^Date:|head -n 1|sed -n 's/.*\([0-9]\{4\}-[0-9][0-9]-[0-9][0-9]\).*/\1/p')
   rev=$(git log -1 --date=short|sed -n 's/^commit \(.*\)/\1/p'|head -n 1)
-  test -z "$date" && echo 1>&2 "Getting GIT version info failed => Falling back to shipped version info"
+  if [ -z "$date" ]; then
+    echo 1>&2 "Getting GIT version info failed => Trying HG"
+    date=$(hg log -l 1 --style=compact|head -n 1|sed -n 's/.*\([0-9]\{4\}-[0-9][0-9]-[0-9][0-9]\).*/\1/p')
+    rev=$( hg log -l 1 --style=compact|head -n 1|sed 's/^.*\( [0-9a-zA-Z]\{12,12\} \).*$/\1/')
+    test -z "$date" && echo 1>&2 "Getting HG version info failed => Falling back to shipped version info"
+  fi
 fi
+
 test -z "$date" && exit 1
 test -z "$rev" && exit 1
 
